export { default as OxxoIcon } from './OxxoIcon'
export { default as SpinPremiaIcon } from './SpinPremiaIcon'
export { default as GordiasIcon } from './GordiasIcon'
export { default as OxxoGasIcon } from './OxxoGasIcon'
export { default as ScorePointsIcon } from './ScorePointsIcon'
export { default as VolarisIcon } from './VolarisIcon'
export { default as ClipboardIcon } from './CopyClipIcon'
